dependencies:
  - name: nginx-ingress
    version: 0.4.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: cert-manager
    version: 0.7.2
    repository: https://charts.jetstack.io