apiVersion: ENC[AES256_GCM,data:R8M=,iv:h3qeyOB8s1ldpLc9eIu8O7e1wifFUAabxSuopaJfnNQ=,tag:w++fbK4bHNJ+YtIIxFBGZA==,type:str]
kind: ENC[AES256_GCM,data:DWh0ERJl,iv:zCOuMKz9jjJfiMIejCTCwHMxOT7FNfO6hmJe3dToUo8=,tag:O4YTx7fsu0L7ojbOBssIQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1b90WJSXpas=,iv:yGiyXkSSTKsXm3018SMiqLumtUd51w7X8f35zvN0mzI=,tag:n8kkpVhBjWg2WM1UeOB7CQ==,type:str]
type: ENC[AES256_GCM,data:kR4H3/4q,iv:JUoWbwW8As3TgrOQpPzfm+xGOj7LfJOMc9mNgoi3Yb8=,tag:U7oph+dcaGkkVwyub1dOZg==,type:str]
#ENC[AES256_GCM,data:rp/kR/CD66etb0VFtTPWFKI8vUrfTpJXNpY/KQBFV8iVY2Rp+WNNcGOGGE2IWxh8t4XW4zhsWKIRI/YcqOr4mgsR0VQgvJM=,iv:adRGcRTDy1foBgYh/hEXTo6lVsov/feRtmkD0WBWjjE=,tag:rKCmWzfLpjNaidhRrCEXxA==,type:comment]
stringData:
    username: ENC[AES256_GCM,data:aQgUsW/sIAzs9u1M3KG4JbA/CY/zKmw=,iv:jY+yOUZIyntmV5Gtcob8LWqE6DaD/SXPuxWmou/jIx8=,tag:z5RPXDPTctPPGGCpr46caw==,type:str]
    password: ENC[AES256_GCM,data:aQX/QpBJ6yz1Vf+3F7snz4BjiIzwqCP7GHf2lwZsRjxIK8Xrp/XaBjnfKDSI1nTGzXD1oO5smr9H2j9DIZp9DpvjZh07GW0KYpE+XC8hNcQKIQYqGuQlSA==,iv:pIBjHJ44V5qtysmflJG4vJhMkLK9Brx2L2OLC1M1sos=,tag:paU6lFoB56Nqou3HHnSy0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-04-25T08:56:00Z'
    mac: ENC[AES256_GCM,data:N++DWK8JeGAO/C5Qv6O+bYsF7KVdO6lGyH1SQW2mJtCeQtN7G6LCKccCrrcsnL7vxeUYgLAb4jmmYr0CH53/W2drgEvFLir3IAzAcYLezk3kUk6vcnYQ7HIDXBk61hR67cFdOjIv/xkscHJAWYQAmMwJaRyJgIGZe9sh0ZluVFg=,iv:cITe7dZDdRrRTPwMU1fLq+4sNPPVFl8wPyj5WuoGhzw=,tag:MHlmQEUDblnswdQJpxTXcQ==,type:str]
    pgp:
    -   created_at: '2019-04-25T08:56:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0rvy2muMaUzAQf/VElNaqdGrs1+xF70hoEeo+LuTDQEzM4Cmlyd8Kj2dFm6
            hwzaoYCDrNewg8FEXwvuFCkz7L5RC5E+exrZiHJm0K1c9Md9oKbpFbYOdl4KCvW7
            EGdUxuCRKyeshVgyirxeeW7M1exCKJdHKxVwz8jJemm4O6515Jln+GEQzuMwJlXW
            5ZOHpyGI9pI5PrdHoA/t/XeTsM/aiDYUEHuqLU0TZOarJSpilx1KQ7vRhxHgZfuQ
            M7rb6KfreirNUmBH9OEM1mp+bp5X+dwKJDmiEX9ydD89keDpltVJXP9yRky/12fs
            xMLrQ17HCCBdZQwwBa05wQZj5OkG2C3mdB2vMqR7s9JeAQxKhBIcbUub1Baazsnk
            +hC/Lsx5oLN4BbczP1e3TYwPf4GpyAR9vTBq9O4TTVcAFBbiPDM+F7J8FjIdC01o
            VG5rA6IT77KiRMdVkmg49jNB6mpGP2U8OEkF/fXJRg==
            =rXXG
            -----END PGP MESSAGE-----
        fp: 9486695DC61BDE40089371BD8F9827A9E3D01026
    unencrypted_suffix: _unencrypted
    version: 3.3.0
