frontend:
  replicas: 1
  # Loadtest config; dev use only
loadtest:
  replicas: 2
  enabled: false
zipkin: 
  enabled:  false
  url: zipkin.zipkin.svc.cluster.local
# CosmosDB -- used in carts-configmap.yaml and user-dep.yaml
cosmosdb:
  accountName: jm-dev-cosmosdb-account
  databaseHostname: jm-dev-cosmosdb-account.documents.azure.com
  databaseName: sockshop
  username: jm-dev-cosmosdb-account
  password: y8CpOjr4tuTZc7gRmEzTBSYrOv07nwNfQgcxVpu1wsc6PlE8WKTCt2tuWM3RqWjqgdEU6lYIKQDSMsfgBCGcSw==
  # Inject this value into the chart referenced in requirements.yaml
  # This way we don't need to download and store the whole nginx-ingress chart; we just refer to it
  # as a dependency and pass it the changes we need
  ### Can be overriden with another values file when deploying w/ Jenkins
# Azure Service Bus -- used in shipping-configmap.yaml
serviceBus:
  namespace: jm-aks
  sasPolicyName:
  sasPolicyKey:
  connectionString: sb://jm-aks.servicebus.windows.net/;SharedAccessKeyName=azsbusfulladmin;SharedAccessKey=9wi7vEYEITeAi1fBdKUAJ9UObNexq5W7DsOlJrpPmvo=
nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: jm-aks
