---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carts
  labels:
    name: carts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: carts
    spec:
      containers:
      - name: carts
        image: weaveworksdemos/carts:0.4.8
        command: ["/usr/local/bin/java.sh"]
        args: ["-jar /usr/src/app/app.jar", "--port=80", "--spring.config.location=/mnt/config/application.properties"]
        env:
         #- name: JAVA_OPTS
         #  value: {{ .Values.java.options }}
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 300m
            memory: 200Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /mnt/config
          name: config-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: config-volume
          configMap:
            defaultMode: 420
            name: cosmosdb-configmap
            items:
            - key: application.properties
              path: application.properties
