---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "orders-configmap"
data:
  application.properties: |
    server.port=${port:8082}
    spring.data.mongodb.uri=mongodb://{{ .Values.cosmosdb.accountName }}:{{ .Values.cosmosdb.password }}@{{ .Values.cosmosdb.databaseHostname }}:10255/data?ssl=true&replicaSet=globaldb
    endpoints.health.enabled=false
    spring.zipkin.baseUrl=http://${zipkin_host:zipkin}:9411/
    spring.zipkin.enabled=${zipkin_enabled:false}
    spring.sleuth.sampler.percentage=1.0
    spring.application.name=orders
    # Disable actuator metrics endpoints
    endpoints.metrics.enabled=false