---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
      - name: user
        image: chrisredfield306/user-azure:0.1.0
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: {{ .Values.cosmosdb.databaseHostname }}:10255
        - name: MONGO_USER
          value: {{ .Values.cosmosdb.username }}
        - name: MONGO_PASS
          value: {{ .Values.cosmosdb.password}}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        #livenessProbe:
          #httpGet:
            #path: /health
            #port: 80
          #initialDelaySeconds: 300
        #readinessProbe:
          #periodSeconds: 3
          #httpGet:
            #path: /health
            #port: 80
          #initialDelaySeconds: 180
          #periodSeconds: 3
