apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: socks-ingress
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{ toYaml . }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80